# This workflow issues automatic approvals from 'github-actions' on a PR if it is ready for review and has the 'auto-approve' label
# This is for situations where something is trivial enough that it's not worth the overhead of a human review
# Also when 'auto-merge' is set, this will allow the PR to be merged automatically
# Use 'auto-approve-merge' to allow both auto-approval and auto-merge in one label and workflow action

name: Automatic PR approval

on:
  pull_request_target:
    types: [synchronize, opened, reopened, labeled, unlabeled, ready_for_review]

jobs:
  auto-approve:
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    if: (contains(github.event.pull_request.labels.*.name, 'auto-approve') || contains(github.event.pull_request.labels.*.name, 'auto-merge') || contains(github.event.pull_request.labels.*.name, 'auto-approve-merge')) && !github.event.pull_request.draft
    steps:
      - name: Automatic PR approval
        if: (contains(github.event.pull_request.labels.*.name, 'auto-approve') || contains(github.event.pull_request.labels.*.name, 'auto-approve-merge')) && !github.event.pull_request.draft
        # Use the REST API to create a silent approval
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews \
          -d '{"event":"APPROVE"}'
      - name: Automatic PR merge
        if: (contains(github.event.pull_request.labels.*.name, 'auto-merge') || contains(github.event.pull_request.labels.*.name, 'auto-approve-merge')) && !github.event.pull_request.draft
        run: |
          gh pr merge --auto $PR_NUMBER -s --repo $GITHUB_REPOSITORY
